### ISSUE TITLE
[regression] 0.6.0 fails to build on FreeBSD: error: "Unsupported OS"

### ISSUE THREAD

**Issue by yurivict** [google/cpu_features#147] opened 2020-11-28 20:38 UTC
```
src/cpuinfo_x86.c:110:2: error: "Unsupported OS"
#error "Unsupported OS"
 ^
src/cpuinfo_x86.c:1268:2: error: "Unsupported fallback detection of SSE OS support."
#error "Unsupported fallback detection of SSE OS support."
 ^
2 errors generated.
```

0.4.0 was building fine.

**Comment by gchatelet** [comment] 2021-06-11 08:37
Duplicate of #158

**Closed by gchatelet** 2021-06-11 08:37 UTC
